## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction

### Creating Tensors

In [ ]:
# Scalar Tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim           # A scalar has no dimensions, it's just a single number

0

In [ ]:
# Get tensor back as py int
scalar.item()

7

In [ ]:
# Vector
vector=torch.tensor([7,7])

In [ ]:
vector.ndim           # Vector has 1 dimension

1

In [ ]:
vector.shape        # shape of vector is 2

torch.Size([2])

In [ ]:
# Matrix
MATRIX=torch.tensor([[7,8],
                     [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim       # Matrix has dimension 2

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape      # Matrix has shape [2, 2]

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR=torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape              # says we have 1 3x3 matrix

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> Update Random Numbers -> Look at data -> Update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0509, 0.4486, 0.6677, 0.5889],
        [0.5462, 0.9495, 0.0830, 0.1304],
        [0.7580, 0.9431, 0.7654, 0.0075]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224, 224, 3))             # height, width, colour channels i.e. RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros, used generally for masking (google what's masking in cv)
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype                  # dtype stands for default data type

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten=torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tens1=torch.arange(start=0, end=1000, step=77)
tens1

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like another tensor (same shape)
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**NOTE:** Tensor datatypes is 1 of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0, 6.0, 9.0],
                             dtype=None,            # what datatype is the tensor, float32 by default for numbers
                             device="cpu",          # what device is your tensor on, e.g. cpu, cuda (gpu), etc.
                             requires_grad=False    # whether or not to track gradiance with this tensor's operations
                             )
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 16 tensor
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor           # sometimes different datatype operations work

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
float_32_tensor*int_32_tensor

tensor([ 9., 36., 72.])

### Tensor datatypes

**NOTE:** Tensor datatypes is 1 of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Create a tensor & finding out details about it
some_tensor = torch.rand(3, 4)

print(f"Dataype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Dataype of tensor: {some_tensor.dtype}")

Dataype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Dataype of tensor: torch.float32


In [ ]:
# tensor.shape and tensor.size() give the same result
print(some_tensor.shape)          # This is an attribute
print(some_tensor.size())         # This is a function

torch.Size([3, 4])
torch.Size([3, 4])


### Manipulating Tensors

It includes:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Matrix multiplication
5. Division

In [ ]:
# Tensor Addition
tensor = torch.tensor([1, 2, 3])
print(tensor+10)                        # will add 10 to all the elements in the tensor: RECOMMENDED
print(torch.add(tensor, 10))            # same result

tensor([11, 12, 13])
tensor([11, 12, 13])


In [ ]:
# Tensor Subtraction
tensor-10               # will subtract 10 from all the elements in the tensor

tensor([-9, -8, -7])

In [ ]:
# Tensor Multiplication (element-wise)
print(tensor * 10)                      # will multiply each elements in the tensor with 10: RECOMMENDED
print(torch.mul(tensor, 10))           # same result

tensor([10, 20, 30])
tensor([10, 20, 30])


### Matrix Multiplication

2 main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication

There are 2 rules which need to be satisfied before performing matrix multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work as 2 not equals to 3 *
* `(2, 3) @ (3, 2)` will work as 3 equals to 3 *
* `(3, 2) @ (2, 3)` will work as 2 equals to 2 *
The above mentioned values are shapes of the tensors.

2. The resulting matrix has the shape of the **outer dimensions**:
*`(2, 3) @ (3,2)` -> `(2, 2)` *
*`(3, 2) @ (2, 3)` -> `(3, 3)`*

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f" Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
 Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
print(torch.matmul(tensor, tensor))           # (1*1) + (2*2) + (3*3) = 14   RECOMMENDED
print(tensor @ tensor)                        # Alternate way

tensor(14)
tensor(14)


### One of the most common errors in deep learning: Shape Errors

In [ ]:
torch.matmul(torch.rand(3,1), torch.rand(4, 2))               # Will throw an error, instead of 1 and 4, there should be a same number

RuntimeError: ignored

In [ ]:
print(torch.matmul(torch.rand(3,2), torch.rand(2, 2)))              # Inner dimensions: 2: same so matrix multiplication is possible
print(torch.matmul(torch.rand(3,2), torch.rand(2, 2)).shape)        # Output tensor will have dimensions = outer dimensions: 3x2

tensor([[0.4475, 0.1979],
        [0.0915, 0.1253],
        [0.5626, 0.3721]])
torch.Size([3, 2])


In [ ]:
# Shapes for matrix multiplication
tensor_a=torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]])
tensor_b=torch.tensor([[7, 10],
                       [8, 11],
                       [9, 12]])

# Will throw an error
torch.mm(tensor_a, tensor_b)              # torch.mm is same as torch.matmul

RuntimeError: ignored

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes of a given tensor

In [ ]:
tensor_b, tensor_b.shape                          # size/shape is 3, 2

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b.T, tensor_b.T.shape                      # Transpose of tensor_b, size/shape is 2, 3

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Now inner dimensions will be equal and = 2, while the output dimension will be outer dimensions: 3x3

torch.matmul(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc. (tensor aggregation)

### It is called tensor aggregation as we are usually converting a larger tensor into a smaller tensor, e.g. taking just the smallest element in a tensor.

In [ ]:
x=torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the min value
torch.min(x)

tensor(0)

In [ ]:
# Alternate way to find the min value
x.min()

tensor(0)

In [ ]:
# Finding the max value
torch.max(x)

tensor(90)

In [ ]:
# Alternate way to find the max value
x.max()

tensor(90)

In [ ]:
# Finding the mean
torch.mean(x)           # will throw an error as datatype is int64 (long)

RuntimeError: ignored

In [ ]:
# Finding the mean        Note that the datatype should be float32
torch.mean(x.type(torch.float32))

In [ ]:
# Alterate way to finding the mean
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Finding the sum
torch.sum(x)

tensor(450)

In [ ]:
# Alternate way to finding the sum
x.sum()

tensor(450)

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()              # Gets the index position of the minimum value

tensor(0)

In [ ]:
x.argmax()              # Gets the index position of the maximum value

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x=torch.arange(1., 10.)               # 1. 10. making it a float
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1, 7)                # Will give an error as input size is 9 when reshaped tensor size is 7

RuntimeError: ignored

In [ ]:
x_reshaped=x.reshape(9, 1)
x_reshaped, x_reshaped.shape

In [ ]:
x=torch.arange(1., 13.)
x_reshaped=x.reshape(3, 4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
x=torch.arange(1., 10.)
x_reshaped=x.reshape(9, 1)

# Change the view
z=x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x as they share the same memory as we opted for .view()
z[:, 0]=5             # Changing the 1st element of z changes the 1st element of x
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x, x, x], dim=0)             # dim (dimension) is 0 by default
x_stacked                                           # They are stacked vertically
# Alternatively, can use torch.vstack([x, x, x]) to stack vertically

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked=torch.stack([x, x, x], dim=1)
x_stacked                                           # They are stacked horizontally
# Alternatively, can use torch.hstack([x, x, x] to stack horizontally)

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions for a target tensor
x_reshaped=x.reshape(1, 9)
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()              # started with 2 [], now only 1, removes all single dimension

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape          # Note that it's 9 and not 1, 9

torch.Size([9])

In [ ]:
# torch.squeeze()
print(f"Original Tensor: {x_reshaped}")
print(f"Shape of Original Tensor: {x_reshaped.shape}")
print(f"\nSqueezed Tensor: {x_reshaped.squeeze()}")
print(f"Shape of Squeezed Tensor: {x_reshaped.squeeze().shape}")
x_squeezed=x_reshaped.squeeze()

Original Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape of Original Tensor: torch.Size([1, 9])

Squeezed Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape of Squeezed Tensor: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0)          # taking dimension as 0
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Tensor Shape: {x_unsqueezed.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Tensor Shape: torch.Size([1, 9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous Target: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=1)           # taking dimension as 1
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Tensor Shape: {x_unsqueezed.shape}")

Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New Tensor Shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x=torch.rand(size=(224, 224, 3))                        # (height, width, color channels)

# Permute (Rearrange) the original tensor to rearrange the axis (or dimension)
x_permuted=x.permute(2, 0, 1)                           # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x.shape}")
print(f"Permuted shape: {x_permuted.shape}")            # this is color channels, height, width

Previous shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [ ]:
# Assigning a random value and seeing if it changes in x_permuted
x[0, 0, 0]=777
x_permuted=x.permute(2, 0, 1)
print(x_permuted[0, 0, 0])                            # x_permuted[0, 0, 0] and x[0, 0, 0] is the same element (visualize the vector)

tensor(777.)


In [ ]:
# Assigning a random value and seeing if it changes in x_permuted
x[0, 2, 0]=777
x_permuted=x.permute(2, 0, 1)
print(x_permuted[0, 2, 0])                            # x_permuted[0, 2, 0] and x[0, 2, 0] is NOT the same element (visualize the vector)

tensor(0.2455)


## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
x=torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index
x[0]        # Indexes on the first bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]               # Alternate way: x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the innermost bracket (last dim)
x[0][0][0]

tensor(1)

In [ ]:
x[1][1][1]            # Will give an error

IndexError: ignored

In [ ]:
x[0][1][1]

In [ ]:
# Getting 9
x[0][2][2]

tensor(9)

In [ ]:
# We can use : to select all of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Getting all values in the 0th and 1st dim but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0][0][:]

tensor([1, 2, 3])

In [ ]:
# Index on x to get 9
x[0][2][2]

tensor(9)

In [ ]:
# Index on x to get 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numeric computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)            # WARNING: when converting from numpy -> PyTorch, pytorch reflects NumPy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype                         # NumPy's default data type is float 64 while PyTorch's default datatype is float32

dtype('float64')

In [ ]:
# Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()               # WARNING: PyTorch's default data type is float32, when converting to NumPy array,
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3, 3)                # Gives different numbers each time

tensor([[0.1585, 0.9212, 0.7126],
        [0.1146, 0.6789, 0.0052],
        [0.3085, 0.7686, 0.4356]])

In [ ]:
# Create 2 random tensors
random_tensor_a=torch.rand(3, 4)
random_tensor_b=torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.5559, 0.6837, 0.8584, 0.4723],
        [0.3083, 0.3712, 0.0442, 0.2265],
        [0.7285, 0.6528, 0.2164, 0.3577]])
tensor([[0.4364, 0.2156, 0.0587, 0.2258],
        [0.7563, 0.9824, 0.3161, 0.0570],
        [0.6046, 0.8765, 0.2711, 0.1335]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
RANDOM_SEED=42                # It can be anything

torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d=torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (with options to upgrade)
2. Use your own GPU - takes a little bit of setup and requires the investment of buying a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers takes a little bit time of setting up, to do this, refer to PyTorch setup documentation

In [1]:
!nvidia-smi                           # Gives info about the GPU, it is running on Tesla T4 GPU right now

Wed Aug 30 05:58:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU Access with PyTorch

In [2]:
import torch
torch.cuda.is_available()               # Will tell if a GPU is available

True

For PyTorch, since it's capable of running compute on both GPU and CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"         # Will tell computer to use GPU if available, else use cpu
device

'cuda'

In [4]:
# Count the number of GPUs
torch.cuda.device_count()
# If we are running a huge model and have multiple GPUs, we may want to run 1 model on 1 GPU and another model on another GPU

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors and models on GPU is because a GPU results in faster computations

In [6]:
# Create a tensor (default on the CPU)
tensor=torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU if available
tensor_on_gpu=tensor.to(device)                 # Shifts the tensor to GPU
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()             # Will throw an error

TypeError: ignored

In [11]:
# To fix the GPU Tensor with NumPy issue, we can first set it to CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu              # Won't throw an error now

array([1, 2, 3])